---

name: Helm Charts Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: read

run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@4ce44398bac0a6f82e55aeb4a753aada3530de5b # v2.7.1
        with:
          tag-name: '${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  load-docker-build-components:
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.load_component.outputs.components }}
      platforms: ${{ steps.load_component.outputs.platforms }}
    env:
      CONFIG_FILE: .qubership/docker-build-config.cfg
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Load Docker Configuration
        id: load_component
        run:  |
          verify=$(cat "$GITHUB_WORKSPACE/${CONFIG_FILE}" | jq '
          def verify_structure:
          .components as $components
          | .platforms as $platforms
          | ($components | type == "array")
          and (all($components[]; has("name") and has("file") and has("context")))
          and ($platforms | type == "string");
          verify_structure
          | if . then true else false end
          ')
          if [ ${verify} == 'true' ]; then
            echo "✅ $GITHUB_WORKSPACE/${CONFIG_FILE} file is valid"
            components=$(jq -c ".components" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
          else
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid"
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo "components=${components}" >> $GITHUB_OUTPUT
          echo "platforms=${platforms}" >> $GITHUB_OUTPUT

  docker-check-build:
    needs: [load-docker-build-components, check-tag]
    name: ${{ matrix.component.name }} dry run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    steps:
      - name: Get version for current component
        id: get-version
        run: |
          echo "IMAGE=${{ matrix.component.name }}" >> $GITHUB_ENV
      - name: Docker build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@4ce44398bac0a6f82e55aeb4a753aada3530de5b # v2.7.1
        with:
          ref: ${{ github.ref }}
          download-artifact: false
          dry-run: true
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
          tags: "${{ env.IMAGE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  chart-release:
    permissions:
      contents: write
      packages: write
    needs: [check-tag, load-docker-build-components, docker-check-build]
    runs-on: ubuntu-latest
    outputs:
      images-versions: ${{ steps.update-versions.outputs.images-versions }}
      charts-artifact: ${{ steps.update-versions.outputs.released-chart-atrifact }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: "Add github.vars into github.env"
        env:
          VARS_JSON: '${{ toJson(vars) }}'
        run: |
          echo "${VARS_JSON}" | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >> $GITHUB_ENV

      - name: "Chart release"
        id: update-versions
        uses: netcracker/qubership-workflow-hub/actions/charts-values-update-action@fix/977-bug-chart-release-process-failed
        with:
          release-version: ${{ inputs.release }}
          config-file: .github/charts-values-update-config.yaml
          default-tag: ${{ inputs.release }}
          package-charts: true
          publish-charts: true

      - name: "Debug"
        env:
          IMAGES_VERSIONS: "${{ steps.update-versions.outputs.images-versions }}"
        run: |
          echo "Images versions: ${IMAGES_VERSIONS}"
          ls -laR

  docker-build:
    name: ${{ matrix.component.name }}
    permissions:
      contents: write
      packages: write
    needs: [chart-release, load-docker-build-components]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    steps:
      - name: Get version for current component
        id: get-version
        env:
          IMAGE_VER: "${{ fromJson(needs.chart-release.outputs.images-versions)[matrix.component.name] || inputs.release }}"
        run: |
          echo "IMAGE_VERSION=${IMAGE_VER}" >> $GITHUB_ENV

      - name: Docker build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@4ce44398bac0a6f82e55aeb4a753aada3530de5b # v2.7.1
        with:
          ref: release-${{ inputs.release }}
          download-artifact: false
          dry-run: false
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
          tags: "${{ env.IMAGE_VERSION }},latest"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  github-release:
    permissions:
      contents: write
      packages: write
    needs: [chart-release, docker-build]
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0
          ref: release-${{ inputs.release }}
          persist-credentials: true

      - name: "Release-drafter"
        uses: netcracker/release-drafter@130c08399304912ffe90e9604e4328f2fdcd7619  # v1.0.1
        with:
          config-name: release-drafter-config.yml
          publish: true
          name: ${{ inputs.release }}
          tag: ${{ inputs.release }}
          version: ${{ inputs.release }}
          commitish: release-${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Download released charts"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          artifact-ids: ${{ needs.chart-release.outputs.charts-artifact }}
      - name: "Upload Assets"
        uses: netcracker/qubership-workflow-hub/actions/assets-action@4ce44398bac0a6f82e55aeb4a753aada3530de5b # v2.7.1
        with:
          tag: ${{ inputs.release }}
          item-path: "./*.tgz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
